# Generated by Django 3.1.4 on 2020-12-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('digital', models.CharField(default='', max_length=10)),
                ('banner', models.CharField(max_length=100)),
                ('data_brands', models.CharField(max_length=100)),
                ('data_vendors', models.CharField(max_length=100)),
                ('data_subdets', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('sub_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(default='[]', max_length=2000)),
                ('digital', models.CharField(default=0, max_length=100)),
                ('banner', models.CharField(max_length=100)),
                ('affiliation', models.IntegerField(default=0)),
                ('affiliation_points', models.FloatField(default=0)),
            ],
        ),
    ]
