# Generated by Django 3.1.4 on 2020-12-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_category_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('sale_price', models.FloatField()),
                ('logo', models.CharField(max_length=100)),
                ('featured', models.CharField(default='ok', max_length=100)),
                ('status', models.CharField(max_length=100, null=True)),
                ('add_timestamp', models.DateTimeField(auto_now_add=True)),
                ('number_of_view', models.IntegerField(default=0)),
                ('category', models.IntegerField(default='')),
                ('sub_category', models.IntegerField(default='', null=True)),
                ('additional_fields', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
    ]
